services:
  postgres:
    container_name: ecom_postgres
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongodb:
    container_name: ecom_mongodb
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - ecom-network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping: 1})"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672" #AMQP
      - "${RABBITMQ_MGMT_PORT}:15672" #Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecom-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  #config server
  config-server:
    build:
      context: ./configserver
    container_name: ecom_config_server
    ports:
      - "${CONFIG_PORT}:8888"
    volumes:
      - ./configserver/src/main/resources/config:/app/config
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped


  # Product service
  product-service:
    build:
      context: ./product

    container_name: ecom_product

    ports:
      - "${PRODUCT_PORT}:8081"
    depends_on:
      postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${PRODUCT_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

    networks:
      - ecom-network
    restart: unless-stopped

  # User service
  user-service:
    build:
      context: ./user

    container_name: ecom_user

    ports:
      - "${USER_PORT}:8082"
    depends_on:
      mongodb:
        condition: service_healthy
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    environment:
      SPRING_MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@ecom_mongodb:27017/${USER_DB}?authSource=admin
      TEST_VAR: hello_from_docker
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

    networks:
      - ecom-network
    restart: unless-stopped

  # Order service
  order-service:
    build:
      context: ./order

    container_name: ecom_order

    ports:
      - "${ORDER_PORT}:8083"
    depends_on:
      postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${ORDER_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

    networks:
      - ecom-network

    restart: unless-stopped

#  pgadmin:
#    container_name: ecom_pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin/data
#    ports:
#      - "5050:80"
#    networks:
#      - ecom-network
#    restart: unless-stopped

networks:
  ecom-network:
    driver: bridge
volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
  #pgadmin_data: