management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true