server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: PRODUCT-SERVICE
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
            - id: USER-SERVICE
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: ORDER-SERVICE
              uri: lb://order-service
              predicates:
                - Path=/api/carts/**,/api/orders/**
